import { StyleSheet } from "react-native";
import { theme } from "../../shared/ui/theme";

export const styles = StyleSheet.create({
  container: {
    padding: theme.spacing.lg,
    paddingBottom: 48,
  },
  header: {
    alignItems: "flex-start",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: theme.spacing.md,
  },
  title: {
    color: theme.colors.darkGray,
    fontSize: 26,
    fontWeight: "800",
    letterSpacing: -0.5,
  },
  subtitle: {
    color: "#555E68",
    fontSize: 14,
    marginTop: 2,
  },
  scheduleButton: {
    alignItems: "center",
    backgroundColor: theme.colors.corporateBlue,
    borderRadius: 16,
    flexDirection: "row",
    gap: 8,
    justifyContent: "center",
    marginBottom: theme.spacing.lg,
    paddingVertical: 14,
    elevation: 3,
  },
  scheduleButtonText: {
    color: theme.colors.white,
    fontSize: 15,
    fontWeight: "700",
  },
  sectionTitle: {
    color: theme.colors.darkGray,
    fontSize: 18,
    fontWeight: "800",
    marginBottom: theme.spacing.sm,
    marginTop: theme.spacing.md,
  },
  agendaSectionHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
    marginTop: 16,
  },
  agendaSectionTitle: {
    color: theme.colors.darkGray,
    fontSize: 16,
    fontWeight: "800",
  },
  agendaSectionCount: {
    color: theme.colors.corporateBlue,
    fontSize: 13,
    fontWeight: "700",
  },
  adminVisitCard: {
    backgroundColor: theme.colors.white,
    borderColor: "#E2EEF8",
    borderRadius: 16,
    borderWidth: 1,
    marginBottom: 8,
    padding: theme.spacing.md,
    elevation: 1,
  },
  adminVisitHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  adminClientName: {
    color: theme.colors.darkGray,
    fontSize: 15,
    fontWeight: "700",
  },
  adminClientAddress: {
    color: "#64748B",
    fontSize: 12,
    marginBottom: 6,
  },
  adminVisitFooter: {
    alignItems: "center",
    borderTopColor: "#F1F5F9",
    borderTopWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingTop: 8,
  },
  adminSystemsCount: {
    color: "#64748B",
    fontSize: 12,
  },
  emptyDayBox: {
    alignItems: "center",
    backgroundColor: "#F8FAFC",
    borderColor: "#E2EEF8",
    borderRadius: 14,
    borderWidth: 1,
    marginBottom: 12,
    padding: 16,
  },
  emptyDayText: {
    color: "#94A3B8",
    fontSize: 13,
  },
  statsRow: {
    flexDirection: "row",
    gap: theme.spacing.md,
    marginBottom: theme.spacing.md,
  },
  moduleCard: {
    backgroundColor: theme.colors.white,
    borderColor: "#E2EEF8",
    borderRadius: 20,
    borderWidth: 1,
    marginBottom: theme.spacing.md,
    padding: theme.spacing.md,
    elevation: 2,
  },
  moduleHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 12,
  },
  moduleIconWrap: {
    alignItems: "center",
    backgroundColor: "#F0F7FD",
    borderRadius: 14,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  moduleTextWrap: {
    flex: 1,
  },
  moduleTitle: {
    color: theme.colors.darkGray,
    fontSize: 16,
    fontWeight: "700",
  },
  moduleBody: {
    color: "#555E68",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 4,
  },
  moduleFooter: {
    alignItems: "center",
    borderTopColor: "#F0F7FD",
    borderTopWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 12,
    paddingTop: 10,
  },
});
