import { StyleSheet } from "react-native";
import { theme } from "../theme";

export const styles = StyleSheet.create({
  card: {
    backgroundColor: theme.colors.white,
    borderColor: theme.colors.lightBlue,
    borderRadius: 16,
    borderWidth: 1,
    marginTop: theme.spacing.md,
    overflow: "hidden",
    shadowColor: "#0876C9",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  header: {
    backgroundColor: "#F4F9FD",
    borderBottomColor: theme.colors.lightBlue,
    borderBottomWidth: 1,
    padding: theme.spacing.md,
  },
  headerLive: {
    backgroundColor: "#ECFDF5",
    borderBottomColor: "#A7F3D0",
  },
  headerTitleRow: {
    alignItems: "center",
    flexDirection: "row",
  },
  iconCircle: {
    alignItems: "center",
    backgroundColor: theme.colors.corporateBlue,
    borderRadius: 999,
    height: 32,
    justifyContent: "center",
    marginRight: 10,
    width: 32,
  },
  iconCircleLive: {
    backgroundColor: "#059669",
  },
  headerTextWrap: { flex: 1 },
  headerTitle: {
    color: theme.colors.darkGray,
    fontSize: 15,
    fontWeight: "700",
  },
  headerSubtitle: {
    color: "#555E68",
    fontSize: 12,
    marginTop: 2,
  },
  coordsBadge: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: theme.colors.white,
    borderColor: theme.colors.lightBlue,
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: "row",
    gap: 4,
    marginTop: 10,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  coordsText: {
    color: theme.colors.corporateBlue,
    fontSize: 12,
    fontWeight: "600",
  },
  actionContainer: {
    padding: theme.spacing.md,
    backgroundColor: "#F0FDF4",
    borderBottomWidth: 1,
    borderBottomColor: "#BBF7D0",
  },
  okButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#059669",
    borderRadius: 10,
    paddingVertical: 12,
  },
  okButtonDisabled: {
    opacity: 0.6,
  },
  okButtonText: {
    color: theme.colors.white,
    fontSize: 15,
    fontWeight: "700",
  },
  mapContainer: {
    backgroundColor: "#EBF3FA",
    height: 220,
    overflow: "hidden",
    width: "100%",
  },
  nativeFallback: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
    padding: theme.spacing.lg,
  },
  fallbackTitle: {
    color: theme.colors.darkGray,
    fontSize: 16,
    fontWeight: "700",
    marginTop: 8,
  },
  fallbackText: {
    color: "#666",
    fontSize: 13,
    marginTop: 4,
  },
  addressRow: {
    alignItems: "center",
    backgroundColor: "#FAFDFE",
    borderBottomColor: theme.colors.lightBlue,
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: 10,
  },
  addressText: {
    color: theme.colors.darkGray,
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
  },
  departureCard: {
    backgroundColor: "#FEF2F2",
    borderTopWidth: 1,
    borderTopColor: "#FECACA",
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  departureText: {
    fontSize: 13,
    color: "#991B1B",
    fontWeight: "600",
  },
  departureCoords: {
    fontSize: 12,
    color: "#7F1D1D",
    marginTop: 2,
  },
  footerRow: {
    alignItems: "center",
    backgroundColor: theme.colors.white,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: theme.spacing.md,
    paddingVertical: 10,
  },
  toggleButton: {
    alignItems: "center",
    flexDirection: "row",
    gap: 6,
    paddingVertical: 4,
  },
  toggleText: {
    color: theme.colors.nearBlack,
    fontSize: 13,
    fontWeight: "600",
  },
  externalLink: {
    alignItems: "center",
    flexDirection: "row",
    gap: 4,
    paddingVertical: 4,
  },
  externalText: {
    color: theme.colors.corporateBlue,
    fontSize: 13,
    fontWeight: "600",
  },
});
